language: csharp
solution: KeePass.sln
before_install:
- sudo apt-get update
- sudo apt-get install -y libmono-system-windows-forms4.0-cil libmono-corlib4.5-cil libmono-system-drawing4.0-cil libmono-system-security4.0-cil libmono-system-xml4.0-cil libmono-system4.0-cil mono-xbuild
script:
- cd Build
- ./SetVersion.sh
- ./SnKeys_UseUnique.sh
- cd ..
- xbuild /p:Configuration=Release KeePass.sln
